### ISSUE TITLE
Priority Queuing System

### ISSUE THREAD

**Issue by broswen** [fix8software/Stonewall#1]
Implement queuing system to give priority to donators and staff members.

- Staff members should instantly connect and should ignore maximum player limit.
- Donators should always connect before regular players but should acknowledge the max limit.
- Regular players should only be connected if the priority queue is empty and should acknowledge the max limit.

Donators are specified as having the `velocityqueue.queue.priority` permission node.
Staff members are specified as having the `velocityqueue.queue.staff` permission node.

Current queue status/information message should never show a "backwards" direction in queue for regular players. Instead keep the minimum and just wait longer.

**Comment by Epicface92** [comment]
Merged #2 with commit d79065ed24f8915d884d59ec996d0c260fd716fd
